---
- hosts: localhost
  tasks:
    - include_role:
        name: arch_bootstrap
      vars:
        main_mirror: https://osl.ugr.es/archlinux
    - include_role:
        name: arch_bootstrap
        tasks_from: create-image
      vars:
        container: "{{ working_container }}"
    - include_role:
        name: arch_bootstrap
        tasks_from: push-to-registry
      vars:
        release: "{{ tarball_result.release }}"
