---
- hosts: localhost
  tasks:
    - include_role:
        name: arch_container
      vars:
        main_mirror: https://osl.ugr.es/archlinux
    - name: Add newly created container to inventory
      add_host:
        name: container
        ansible_host: "{{ working_container }}"
        ansible_connection: buildah
        ansible_python_interpreter: /usr/bin/python3

- hosts: container
  gather_facts: false
  tasks:
    - include_role:
        name: arch_container
        tasks_from: pacman-keyring
    - name: Ensure Python is installed
      raw: pacman -Syu --noconfirm --needed python
    - name: Ensure basic GNU utilities are present
      pacman:
        name:
          - coreutils
          - grep
          - sed
          - less
          - gzip
          - tar
          - findutils
        state: present
