---
- hosts: localhost
  vars_files:
    - vars/registry.yml
  tasks:
    - include_role:
        name: arch_bootstrap
    - name: Login to registry
      command: buildah login -u {{ registry.user }} --password-stdin {{ registry.name }}
      args:
        stdin: "{{ registry.password }}"
    - name: Commit changes in container to an image on the registry
      command: >
        buildah commit {{ buildah_from.stdout }}
        docker://{{ registry.name }}/{{ registry.repo }}:{{ release }}
