---
- hosts: localhost
  tasks:
    - name: ID of container is {{ working_container }}
      add_host:
        name: container
        ansible_host: "{{ working_container }}"
- hosts: container
  gather_facts: false
  tasks:
    - include_role:
        name: arch_container
        tasks_from: pacman-keyring
    - name: Ensure Python is installed
      raw: pacman -Syu --noconfirm --needed python
      register: python_install
      changed_when: python_install.stdout is not search('there is nothing to do')
    - name: Ensure basic GNU utilities are present
      pacman:
        name: "{{ gnu_utils }}"
        state: present
    - include_role:
        name: common
        tasks_from: "{{ item }}"
      loop: "{{ common_tasks }}"
