---
- hosts: localhost
  tasks:
    - name: Add container to inventory
      add_host:
        name: container
        ansible_host: "{{ working_container }}"
        ansible_connection: buildah
- hosts: container
  gather_facts: false
  tasks:
    - include_role:
        name: arch_container
        tasks_from: pacman-keyring
    - name: Ensure Python is installed
      raw: pacman -Syu --noconfirm --needed python
    - name: Ensure basic GNU utilities are present
      pacman:
        name:
          - coreutils
          - grep
          - sed
          - less
          - gzip
          - tar
          - findutils
        state: present
    - include_role:
        name: common
        tasks_from: "{{ item }}"
      loop:
        - locale
        - timezone
      vars:
        timezone: Europe/Madrid
