version: 2.1

executors:
  ubuntu:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  test-docker:
    executor: ubuntu
    steps:
      - checkout

workflows:
  pull_request:
    jobs:
      - test-docker
