aliases:
  - &setup
      - install-deps
      - checkout

version: 2.1

commands:
  install-deps:
    steps:
      - run:
          name: Add repositories with Ansible and buildah packages
          shell: sudo /bin/bash -eo pipefail
          command: |
            apt update
            apt --yes install software-properties-common
            apt-add-repository --yes ppa:ansible/ansible
            apt-add-repository --yes ppa:projectatomic/ppa
            apt update
      - run:
          name: Install dependencies
          command: sudo apt --yes install ansible buildah

executors:
  ubuntu:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  test_job_3:
    executor: ubuntu
    steps:
      - run:
          name: Pull roles from repository
          command: |
            pip install python-gilt
            gilt overlay
      - run:
          name: Build a container and save image to file
          shell: sudo /bin/bash -eo pipefail
          command: |
            ansible-playbook build.yml
            buildah commit working-container oci-archive:foo:latest
      - run:
          command: ls -la

workflows:
  pull_request:
    jobs:
      - test_job_3:
          pre-steps: *setup
