superuser: &sudo_shell
  shell: sudo -EH /bin/bash -leo pipefail
  environment:
    - BASH_ENV: "~/.profile"

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Setup environment variables
          command: |
            FIRST_OF_MONTH_DATE=$(date +'%Y.%m.01')
            echo "export BASE_URL=https://archive.archlinux.org/iso/${FIRST_OF_MONTH_DATE}/" >> $BASH_ENV
            echo "export TARBALL=archlinux-bootstrap-${FIRST_OF_MONTH_DATE}-x86_64.tar.gz" >> $BASH_ENV
            echo "export SHA1SUMS=sha1sums.txt" >> $BASH_ENV
            echo "export CONTAINER=arch" >> $BASH_ENV
            echo "export IMAGE_REF=docker://${REGISTRY}/${REPOSITORY}:${FIRST_OF_MONTH_DATE}" >> $BASH_ENV
            cat < $BASH_ENV | sudo tee -a /root/.profile
      - run:
          name: Download Arch Linux bootstrap tarball and checksum
          command: |
            cat <<EOF | wget --base="$BASE_URL" -i -
            $TARBALL
            $SHA1SUMS
            EOF
      - run:
          name: Check file integrity
          command: grep $TARBALL $SHA1SUMS | sha1sum -c -
      - run:
          name: Add projectatomic repository
          <<: *sudo_shell
          command: |
            apt-get update
            apt-get -y install software-properties-common
            add-apt-repository -y ppa:projectatomic/ppa
            apt-get update
      - run:
          name: Install buildah and skopeo
          command: sudo apt-get -y install buildah skopeo
      - run:
          name: Extract tarball to a new empty container
          <<: *sudo_shell
          command: |
            buildah from --name $CONTAINER scratch
            ROOT_FS=$(buildah mount $CONTAINER)
            tar xz -f $TARBALL --strip-components=1 -C $ROOT_FS
            buildah config --cmd /bin/bash $CONTAINER
            buildah unmount $CONTAINER
      - run:
          name: Create image from container and push it to registry
          <<: *sudo_shell
          command: |
            echo $REGISTRY_PWD | buildah login -u $REGISTRY_USER --password-stdin $REGISTRY
            buildah commit $CONTAINER $IMAGE_REF
      - run:
          name: Inspect result
          command: sudo skopeo inspect $IMAGE_REF
