version: 2.1

commands:
  setup:
    parameters:
      pull-roles:
        type: boolean
        default: true
    steps:
      - run:
          name: Create a directory to mount containers' overlay file system
          command: mkdir ~/mycontainer
      - checkout
      - when:
          condition: << parameters.pull-roles >>
          steps:
            - run:
                name: Pull roles from repository
                command: |
                  pip install python-gilt
                  gilt overlay

executors:
  ubuntu:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  build:
    executor: ubuntu
    steps:
      - run:
          name: "Run playbooks: build.yml, provision.yml and cleanup.yml"
          command: docker run --net=host --privileged -v ~/mycontainer:/var/lib/containers:Z -v ~/project:$BUILD_DIR --env BUILD_DIR docker.io/miquecg/ansible-buildah run build.yml provision.yml cleanup.yml
  push:
    executor: ubuntu
    steps:
      - run:
          name: Run detached container to execute next steps
          command: docker run --detach --name=runner --net=host --privileged -v ~/mycontainer:/var/lib/containers:Z -v ~/project:$BUILD_DIR --env-file .circleci/env.list docker.io/miquecg/ansible-buildah sh -c 'while true ; do sleep 100000 ; done'
      - run:
          name: Create a barebones container
          command: docker exec -w $BUILD_DIR runner buildah from --name foo scratch
      - run:
          name: Save its image on a remote registry
          command: docker exec -w $BUILD_DIR runner ansible-playbook commit.yml --extra-vars "container=foo tag=1.23.45"
  main:
    executor: ubuntu
    steps:
      - run:
          name: Run main.yml playbook
          command: sudo -E ansible-playbook main.yml

workflows:
  pull_request:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
          pre-steps:
            - setup
      - push:
          filters:
            branches:
              ignore: master
          pre-steps:
            - setup:
                pull-roles: false
  merge:
    jobs:
      - main:
          filters:
            branches:
              only: master
          pre-steps:
            - setup
