version: 2.1

commands:
  setup:
    parameters:
      pull-roles:
        type: boolean
        default: true
    steps:
      - run:
          name: Create a directory to mount containers' overlay file system
          command: mkdir ~/mycontainer
      - checkout
      - when:
          condition: << parameters.pull-roles >>
          steps:
            - run:
                name: Pull roles from repository
                command: |
                  pip install python-gilt
                  gilt overlay

executors:
  ubuntu:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  build:
    executor: ubuntu
    steps:
      - run:
          name: Build a container
          command: docker run --net=host --privileged -v ~/mycontainer:/var/lib/containers:Z -v ~/project:$BUILD_DIR --env BUILD_DIR docker.io/miquecg/ansible-buildah run build.yml provision.yml cleanup.yml
  push:
    executor: ubuntu
    steps:
      - run:
          name: Create a barebones container
          command: buildah from --name foo scratch
      - run:
          name: Save container image on a remote registry
          command: ansible-playbook commit.yml --extra-vars "container=foo tag=1.23.45"
  main:
    executor: ubuntu
    steps:
      - run:
          name: Run main.yml playbook
          command: sudo -E ansible-playbook main.yml

workflows:
  pull_request:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
          pre-steps:
            - setup
      - push:
          filters:
            branches:
              ignore: master
          pre-steps:
            - setup:
                pull-roles: false
  merge:
    jobs:
      - main:
          filters:
            branches:
              only: master
          pre-steps:
            - setup
