superuser: &sudo_shell
  shell: sudo /bin/bash -eo pipefail

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Add projectatomic repository
          <<: *sudo_shell
          command: |
            apt-get update
            apt-get -y install software-properties-common
            add-apt-repository -y ppa:projectatomic/ppa
            apt-get update
      - run:
          name: Install buildah and skopeo
          command: sudo apt-get -y install buildah skopeo
