version: 2.1

executors:
  ubuntu:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  test-docker:
    executor: ubuntu
    steps:
      - checkout
      - run: docker pull quay.io/buildah/stable:latest
      - run: docker images
      - run: mkdir mycontainer
      - run: docker run --detach --name=buildahctr --net=host --privileged -v ~/project/mycontainer:/var/lib/containers:Z quay.io/buildah/stable sh -c 'while true; do sleep 100000; done'
      - run: docker ps
      - run: docker exec buildahctr buildah from alpine
      - run: ls -la ~
      - run: ls -la ~/project

workflows:
  pull_request:
    jobs:
      - test-docker
