superuser: &sudo_shell
  shell: sudo /bin/bash -eo pipefail

version: 2
jobs:
  build_container:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          command: pip install python-gilt
      - checkout
      - run:
          command: gilt overlay
      - run:
          command: find -path ./.git -prune -o -type d,f

workflows:
  version: 2
  ansible:
    jobs:
      - build_container:
          filters:
            branches:
              ignore: master
