superuser: &sudo_shell
  shell: sudo /bin/bash -eo pipefail

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Setup environment variables
          command: |
            echo 'export DATE=$(date +"%Y.%m.01")' >> $BASH_ENV
            echo 'export ARCHITECTURE="x86_64"' >> $BASH_ENV
            echo 'export FILENAME="archlinux-bootstrap-${DATE}-${ARCHITECTURE}.tar.gz"' >> $BASH_ENV
            echo 'export URL_PATH="https://archive.archlinux.org/iso/${DATE}"' >> $BASH_ENV
            echo 'export CONTAINER="arch"' >> $BASH_ENV
      - run:
          name: Download Arch Linux bootstrap tarball
          command: >
            wget
            ${URL_PATH}/${FILENAME}
            ${URL_PATH}/${FILENAME}.sig
            ${URL_PATH}/sha1sums.txt
      - run:
          name: Check file integrity
          command: grep $FILENAME sha1sums.txt | sha1sum -c -
      - run:
          name: Add projectatomic repository
          <<: *sudo_shell
          command: |
            apt-get update
            apt-get -y install software-properties-common
            add-apt-repository -y ppa:projectatomic/ppa
            apt-get update
      - run:
          name: Install buildah
          command: sudo apt-get -y install buildah
      - run:
          name: Extract tarball to a new empty container
          <<: *sudo_shell
          command: |
            buildah from --name $CONTAINER scratch
            ROOT_FS=$(buildah mount $CONTAINER)
            tar xz -f $FILENAME --strip-components=1 -C $ROOT_FS
            buildah config --cmd /bin/bash $CONTAINER
            buildah unmount $CONTAINER
      - run:
          name: Create image from container and push it to registry
          <<: *sudo_shell
          command: |
            echo $REGISTRY_PWD | buildah login -u $REGISTRY_USER --password-stdin $REGISTRY
            buildah commit $CONTAINER docker://${REGISTRY}/${REPOSITORY}:${DATE}
      - run:
          name: Inspect result
          command: sudo skopeo inspect docker://${REGISTRY}/${REPOSITORY}:${DATE}
