superuser: &sudo_shell
  shell: sudo /bin/bash -eo pipefail

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Add repositories for build dependencies
          <<: *sudo_shell
          command: |
            apt update
            apt --yes install software-properties-common
            apt-add-repository --yes ppa:ansible/ansible
            apt-add-repository --yes ppa:projectatomic/ppa
            apt update
      - run:
          name: Install build dependencies
          command: sudo apt --yes install ansible buildah skopeo
