superuser: &sudo_shell
  shell: sudo /bin/bash -eo pipefail

version: 2.1

jobs:
  build_container:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Add repositories with build dependencies
          <<: *sudo_shell
          command: |
            apt update
            apt --yes install software-properties-common
            apt-add-repository --yes ppa:ansible/ansible
            apt-add-repository --yes ppa:projectatomic/ppa
            apt update
      - run:
          name: Install build dependencies
          command: |
            sudo apt --yes install ansible buildah
            pip install python-gilt
      - checkout
      - run:
          name: Pull roles from repository
          command: gilt overlay
      - run:
          name: Run playbook
          command: sudo -E ansible-playbook main.yml

workflows:
  ansible:
    jobs:
      - build_container:
          filters:
            branches:
              ignore: master
