superuser: &sudo_shell
  shell: sudo /bin/bash -eo pipefail

version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Add repositories with build dependencies
          <<: *sudo_shell
          command: |
            apt update
            apt --yes install software-properties-common
            apt-add-repository --yes ppa:ansible/ansible
            apt-add-repository --yes ppa:projectatomic/ppa
            apt update
      - run:
          name: Install build dependencies
          command: |
            sudo apt --yes install ansible buildah
            pip install python-gilt
      - checkout
      - run:
          name: Pull roles from repository
          command: gilt overlay
      - run:
          name: Build a container
          command: sudo -E ansible-playbook build.yml provision.yml cleanup.yml
  push:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Add repositories with build dependencies
          <<: *sudo_shell
          command: |
            apt update
            apt --yes install software-properties-common
            apt-add-repository --yes ppa:ansible/ansible
            apt-add-repository --yes ppa:projectatomic/ppa
            apt update
      - run:
          name: Install build dependencies
          command: sudo apt --yes install ansible buildah
      - checkout
      - run:
          name: Create a barebones container
          command: buildah from --name foo scratch
      - run:
          name: Write a new image and push it to registry
          command: ansible-playbook commit.yml --extra-vars "container=foo tag=1.23.45"

workflows:
  pull_request:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - push:
          filters:
            branches:
              ignore: master
